---
  - name: Install packages
    tags:
      - config
      - packages
    become: yes
    apt:
      name={{ item }}
      update_cache=yes
      cache_valid_time=3600
      state=present
    with_items:
      - acl
      - bash-completion
      - build-essential
      - curl
      - dnsutils
      - fail2ban
      - htop
      - iotop
      - mosh
      - openssl
      - unzip
      - vim
      - zip

  # Remove when Ansible 2.1 is available for the apt module. See http://docs.ansible.com/ansible/apt_module.html
  - name: Autoremove unused packages
    tags:
      - config
      - packages
    become: yes
    command: apt-get -y autoremove
    register: autoremove_output
    changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"
