---
  - name: Set up authorised keys from GitHub
    tags:
      - config
      - ssh
    authorized_key:
      user={{ admin_user }}
      key={{ item }}
      state=present
    with_items: "{{admin_authorized_keys}}"

  - name: Disallow root SSH access
    tags:
      - config
      - ssh
    become: yes
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp="^PermitRootLogin"
      line="PermitRootLogin no"
      state=present
    notify:
      - restart sshd

  - name: Disallow SSH password authentication
    tags:
      - config
      - ssh
    become: yes
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp="^PasswordAuthentication"
      line="PasswordAuthentication no"
      state=present
    notify:
      - restart sshd
    when: admin_user != "vagrant"

  - name: allow deploy user
    tags:
      - config
      - ssh
    become: yes
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp="^AllowUsers"
      line="AllowUsers {{ allowed_users | join(' ') }}"
      state=present
    notify:
      - restart sshd
