# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/xenial64'

  config.vm.define 'app', primary: true do |host|
    # IP must match that in ../ansible/inventories/dev.hosts
    host.vm.network 'private_network', ip: '192.168.52.2'
    host.vm.hostname = "dev-vending-machine.chrisyallop.com"

    host.vm.provider "virtualbox" do |v|
      v.memory = 1024

      # Added to help identify in VirtualBox if manually setting CPU count & enabling SSD for further performance
      v.name = "dev-vending-machine.chrisyallop.com"
    end
  end

  config.vm.synced_folder "../../", "/var/www/vending-machine", type: "nfs"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook        = "../ansible/site.yml"
    ansible.inventory_path  = "../ansible/inventories/dev.hosts"
    ansible.limit           = "all"
  end
end
