<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Vending Machine</title>

        <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

        <style type="text/css">
            .price {
                font-family: 'Kaushan Script', cursive;
                font-size: 135px;
            }
        </style>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <br/>
        <div class="container">
            <?php if (isset($sellingPrice)) : ?>

                <div class="row">
                    <div class="col-md-4"><h1><span class="label label-danger">Selling Price</span></h1></div>
                    <div class="col-md-4"><p class="price text-danger"><?= htmlspecialchars($sellingPrice); ?>p</p></div>
                    <div class="col-md-4">
                        <?php if (isset($startingInventory) && is_array($startingInventory)) : ?>
                            <div class="panel panel-danger">
                                <div class="panel-heading">
                                  <h3 class="panel-title">Starting Inventory</h3>
                                </div>
                                <div class="panel-body">

                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>Denomination</th>
                                                <th>Quantity</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach ($startingInventory as $denomination => $quantity) : ?>
                                            <tr>
                                                <th><?= htmlspecialchars($denomination); ?></th>
                                                <td><?= htmlspecialchars($quantity); ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <hr/>

                <div class="row">
                    <div class="col-md-4"><h1><span class="label label-default">Payment Amount</span></h1></div>
                    <div class="col-md-4">
                        <form method="get" accept-charset="utf-8" action="/" enctype="application/x-www-form-urlencoded">

                            <div class="form-group">
                                <div class="input-group">
                                  <input type="number" name="purchaseAmount" min="<?= htmlspecialchars($sellingPrice); ?>" class="form-control input-lg" placeholder="Amount" value="<?= isset($purchaseAmount) ? $purchaseAmount : '' ?>">
                                  <div class="input-group-addon">p</div>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary btn-lg btn-block">Pay</button>
                        </form>
                    </div>
                    <div class="col-md-4">&nbsp;</div>
                </div>

                <?php if (isset($change) && is_array($change->getCoins())) : ?>

                    <hr/>

                    <div class="row">
                        <div class="col-md-4"><h1><span class="label label-success">Change Amount</span></h1></div>
                        <div class="col-md-4">
                            <p class="price text-success"><?= htmlspecialchars($change->getAmount()); ?>p</p>

                            <?php if ($change->getAmount() > 0) : ?>
                                <div class="panel panel-success">
                                    <div class="panel-heading">
                                      <h3 class="panel-title">Change Denominations</h3>
                                    </div>
                                    <div class="panel-body">

                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Denomination</th>
                                                    <th>Quantity</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <?php foreach ($change->getCoins() as $denomination => $quantity) : ?>
                                                <tr>
                                                    <th><?= htmlspecialchars($denomination); ?></th>
                                                    <td><?= htmlspecialchars($quantity); ?></td>
                                                </tr>
                                            <?php endforeach; ?>
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                            <?php endif; ?>

                        </div>
                        <div class="col-md-4">

                            <?php if (isset($closingInventory) && is_array($closingInventory)) : ?>
                                <div class="panel panel-success">
                                    <div class="panel-heading">
                                      <h3 class="panel-title">Closing Inventory</h3>
                                    </div>
                                    <div class="panel-body">

                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Denomination</th>
                                                    <th>Quantity</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <?php foreach ($closingInventory as $denomination => $quantity) : ?>
                                                <tr>
                                                    <th><?= htmlspecialchars($denomination); ?></th>
                                                    <td><?= htmlspecialchars($quantity); ?></td>
                                                </tr>
                                            <?php endforeach; ?>
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                            <?php endif; ?>

                        </div>
                    </div>

                <?php endif; ?>

            <?php else: ?>
                Vending machine is offline
            <?php endif; ?>
        </div>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </body>
</html>
