#!/usr/bin/env bash

# Install application dependencies
cd /home/vagrant/vending-machine
composer install

# Add code coverage support for PHPUnit
if test ! -f /etc/php/7.0/cli/conf.d/20-xdebug.ini; then
	echo "zend_extension=xdebug.so" | sudo tee /etc/php/7.0/cli/conf.d/20-xdebug.ini
	sudo service php7.0-fpm restart
fi
